# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4845a0d32f5cad941776308f7e7bcd0d41aeaa267d96aba71d7fa888497bb78bc2dee1dde8affe950e63b0d2487d25e858c1ce67932d4516bb675cc09605d9e6

test:
  secret_key_base: 5bb29eedf719dc302f08daa9665e26825ba78d4cff133a2c63c0bfe9cf7b788b2f204bbf3249907a9cb726b12cd4a389c84b74d2bd839a7fe3f60b56aa95323b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
